version: '3.8'

services:
  springboot-app:
    build: .
    container_name: springboot-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=production
    networks:
      - spring-net

  # Optional: Add a database if your app needs one
  # postgres:
  #   image: postgres:13-alpine
  #   environment:
  #     POSTGRES_PASSWORD: yoursecurepassword
  #     POSTGRES_DB: springdb
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   networks:
  #     - spring-net

networks:
  spring-net:
    driver: bridge

# volumes:
#   postgres-data:
